### ISSUE TITLE
Add repeater field support

### ISSUE THREAD

**Issue by jeremymouton** [aspendigital/october-lookfeel#2]
OctoberCMS now supports repeater fields with the StaticPage plugin.

http://octobercms.com/docs/services/parser#dynamic-syntax-parser

When I setup these content fields and try to save, the LookFeel plugin trips:

![screen shot 2016-10-07 at 11 39 00 am](https://cloud.githubusercontent.com/assets/1574433/19199985/e6aeb2ba-8c83-11e6-96d6-b2aaa25d988b.png)

I am using the following markup in my layout:

```
{repeater name="content_sections" prompt="Add another content section"}
  <h2>{text name="title" label="Title"}Title{/text}</h2>
  <p>{textarea name="content" label="Content"}Content{/textarea}</p>
{/repeater}
```

**Comment by jimcottrell** [comment]
See how b8025603d50b94179bea7e6bca59916f63b933a7 works for you.

**Comment by jimcottrell** [comment]
I guess that only fixed the field loading, not saving.  Try the latest commit.

**Comment by jeremymouton** [comment]
That did it! Thanks!
