### ISSUE TITLE
Add Pages List to Static Pages fields

### ISSUE THREAD

**Issue by jeremymouton** [aspendigital/october-lookfeel#7]
Is it possible to create a new form field type to get a list of existing pages in the backend?

Something like this:

<img width="1367" alt="screen shot 2017-04-21 at 10 36 39 am" src="https://cloud.githubusercontent.com/assets/1574433/25287518/e2144e0a-267e-11e7-9b29-799835151471.png">

This would allow clients to easily link custom content to existing site pages instead of needing to find and copy/paste absolute URLs. 

Parser docs: http://octobercms.com/docs/services/parser#dynamic-syntax-parser

**Comment by jimcottrell** [comment]
@jeremymouton, try out our forked Pages plugin [page-picker-widget](/aspendigital/pages-plugin/tree/page-picker-widget) branch, which adds a "pagepicker" field type.  If that works for you, I'll make a pull request upstream.  If it's not accepted, I'll add it to lookfeel.

**Comment by jimcottrell** [comment]
Correction, the type is now "staticpagepicker."  Probably a more fitting name.

**Comment by jimcottrell** [comment]
Merged in upstream Pages plugin.
