### ISSUE TITLE
CMS sidebar issue (edge)

### ISSUE THREAD

**Issue by petehalverson** [aspendigital/october-lookfeel#8]
When using the October CMS Edge build (aspendigital/octobercms:edge), the CMS sidebar styles are off.

Edge without LookFeel:
![screen shot 2017-11-07 at 5 27 19 pm](https://user-images.githubusercontent.com/911099/32525334-33c23424-c3e1-11e7-9372-003794823b73.png)

Edge with LookFeel:
![screen shot 2017-11-07 at 5 27 24 pm](https://user-images.githubusercontent.com/911099/32525335-33db66ba-c3e1-11e7-9210-756466315655.png)

**Comment by jeremymouton** [comment]
This actually is related to the Backend Skin, not LookFeel. 

Fixed on `ssh://office.aspendigital.com/git/october-backend.git`; `edge` branch.
